### ISSUE TITLE
CCF Portal: ASCT+B Reporter incorrect link 

### ISSUE THREAD

**Issue by kebelhar** [hubmapconsortium/ccf#2]
On the CCF Portal (https://hubmapconsortium.github.io/ccf/) when clicking on the ASCT+B Reporter link, it loads VHMOOC instead of the ASCT+B Reporter.

**Comment by lecross** [comment]
You may need to refresh. Fix is live.
________________________________
From: Kirk Ebelhar ***@***.***>
Sent: Wednesday, March 31, 2021 7:49 AM
To: hubmapconsortium/ccf ***@***.***>
Cc: Cross, Leonard Edward ***@***.***>; Assign ***@***.***>
Subject: [hubmapconsortium/ccf] CCF Portal: ASCT+B Reporter incorrect link (#2)


On the CCF Portal (https://hubmapconsortium.github.io/ccf/) when clicking on the ASCT+B Reporter link, it loads VHMOOC instead of the ASCT+B Reporter.

**Comment by kebelhar** [comment]
Looks good now, thanks.
